### ISSUE TITLE
Request:Find Filtering.

### ISSUE THREAD

**Issue by KomradeSpectre** [Rusketh/ExpAdv2#234]
Currently there is no way to filter a find to include multiple classes, and filter it once more to find the owner of the props. This currently makes me have to write multiple workarounds to filter them manually, rather than inputting a simple function to filter them e.g E2's FindClipToClass, FindIncludeClass,etc. I would like to request a way to filter the find to remove workaround redundancy.

**Comment by thegrb93** [comment]
An optional delegate parameter would be good. Return true in the delegate to add entity to array, return false to filter.

**Comment by Orzlar** [comment]
'
array Find = findByGlass("prop_*")

**Comment by DaedalusGame** [comment]
Dependent on the server you're running this on, finding all prop_* and gmod_* on the server is not a very good idea. Every findByClass will iterate through everything that exists on the server. There may be hundreds or thousands of things on the server. You will do this twice, so you will iterate 2000 times. Not only that, but your code will also concatenate two arrays. This means you iterate 3000 times. And finally you iterate through the list of found objects, bringing the amount of iterations up to 4000. BUT WAIT: there's more! You also check if the owner of the object is within a blacklist. (sic: p:Whitelist in the foreach btw) If you have 8 players currently on you will run that one check (p == v.Owner()) 32000 times regardless.

Dependent on the language used, this may actually be insignificant. In Expression 2 it certainly wasn't. I built a shield that would iterate through as many classes as I could, using the built-in includes. I would then iterate and do a simple calculation for intersecting a ray with a sphere and a few simple distance checks. I would also break out of the loop when I hit my maximum number of shield bits but the chip would still crash under very high propcounts on the server, because the find itself was hitting the tick quota.

While ExpAdv2 may not be like this because it compiles to lua (from what I understand) and lua is blazing fast (most of the time), it's still very inefficient to find everything and then do list concatenations instead of one filtered lookup. The question is how the lookup would be performed, @thegrb93 suggested a delegate as a parameter. Delegates in lua do not exist. But any function in lua is an object so I assume it just uses the ability to store functions in variables to call it as a delegate. Sometimes I code in BYOND as a joke, and ironically, procedure calls are very expensive and produce a lot of overhead in that language. It makes sense, considering that every call to a function will create a new stackframe and the system has to take care of it. In BYOND procs have all kinds of special variables, but this is not BYOND, this is ExpAdv2 and (maybe) lua. Where as I? Oh yes, function calls in lua would probably not be very expensive. So an optional delegate to find functions would probably be a good thing. Failing that, there's a few other ways to make an acceptable filtered iteration. Like hardcoded checks. Checks tend to be fairly inexpensive.

**Comment by Damianu** [comment]
http://wiki.garrysmod.com/page/ents/FindByClass
There is no difference between filtering in EA2, as you know it compiles to lua. Thing you don't know it would get all entities and filter class inside lua anyway. There are no filters in GLua. So code that orzlar wrote would have similar speed to internal function, it will do same thing.

**Comment by DaedalusGame** [comment]
(Which is btw what I told Komrade prior to him posting this request)

**Comment by Orzlar** [comment]
What.. It was just an example.

**Comment by Rusketh** [comment]
See, the thing is, its both easier and faster to filter the results yourself.
