### ISSUE TITLE
"global" prefix does not work

### ISSUE THREAD

**Issue by TimeSchocK** [Rusketh/ExpAdv2#287]
As title suggests global prefix does not make a variable available out of ist block
example:

    if(true){
    global int A = 1
    }
    int B = A

throws error: variable A does not exist

**Comment by Extra-Mental** [comment]
I think global is used to share a variable across chips on a server, like a gTable in E2. But even without global you are still defining A inside a block that can't be accessed outside.

You need to define A as an int outside the block before modifying it.

    int A
    if(true){
          A = 1
    }
    int B = A

This is because if your if statement ever returned false, A would not be defined as int causing B to try and set itself to an undefined variable.

**Comment by bigdogmat** [comment]
That would make sense though the way it was explained in the tut videos anything with a global flag can be accessed anywhere in the chip, though when he tried to use it in the tut videos it didn't work...

**Comment by TimeSchocK** [comment]
Thank you Extra-Mental,
I'm trying to switch over from E2 with only little experience in Java.
It's getting a bit difficult without a full documentation

**Comment by VINTproYKT** [comment]
This might be a bug, cause tutorial tells:
> ... this modifier will make a variable global, meaning it will be accessible anywhere in your code below the line where the variable is defined and thus the variable will no longer be nested to its current block of code.
