### ISSUE TITLE
Move compiling to clientside

### ISSUE THREAD

**Issue by suunrider** [Rusketh/ExpAdv2#324]
Whole compiling should be done on client so the server doesn't get at least the lag

**Comment by bigdogmat** [comment]
Issue with this is that then the client can send fake scripts to the server, the reason it's compiled on the server is so it can be validated.

**Comment by suunrider** [comment]
What do you mean with fake scripts?

**Comment by bigdogmat** [comment]
The server would have to receive the script to run it, and or send it to other clients for the clientside portion. The issue is a player could easily send a fake script to run all kinds of things on the server and or clients if it gets sent to them. Only way to fix that would be to validate the script received or sandbox it which would probably be more work than just compiling it on the server and wouldn't be as secure.

**Comment by suunrider** [comment]
Okay. Then I can only remove expadv and wait for ea3.. (go work rusketh)
